# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Opslevel Command Line Utility"
  homepage "https://www.opslevel.com/"
  version "0.1.0-beta.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v0.1.0-beta.4/opslevel-darwin-amd64.tar.gz"
      sha256 "887eff6fc828da6d5ee5809022328e17fa189ab086ecad4494b91ee0506471cc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpsLevel/cli/releases/download/v0.1.0-beta.4/opslevel-darwin-arm64.tar.gz"
      sha256 "05fb3a570bfe38327cd292f22101b385d78ba70294abb8112617fe31691dd28b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v0.1.0-beta.4/opslevel-linux-amd64.tar.gz"
      sha256 "5f7ff4486f770c1c35fc59a9d9c9f936951b4f0ef5175647b77bb377a1259306"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v0.1.0-beta.4/opslevel-linux-arm.tar.gz"
      sha256 "41391607fd5a8d3e2b001e04aa09a696f60d778f37bfdd760abadb08a9b59628"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v0.1.0-beta.4/opslevel-linux-arm64.tar.gz"
      sha256 "609d36e4d04fdbef0087fae46a2366175071b8153cb5278830c733734b95e968"
    end
  end

  depends_on "jq"

  def install
    bin.install "opslevel"
  end

  test do
    system "#{bin}/opslevel version"
  end
end
