# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Opslevel Command Line Utility"
  homepage "https://www.opslevel.com/"
  version "0.3.0-beta.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v0.3.0-beta.5/opslevel-darwin-amd64.tar.gz"
      sha256 "70d129db288cb6aa188f5a8698b2cb45ec556aad787aa8853123506be535a105"
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpsLevel/cli/releases/download/v0.3.0-beta.5/opslevel-darwin-arm64.tar.gz"
      sha256 "9529eddd71e985121b46f595538e48b1b9d24768f0382b54a607a1c60ef3d88d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v0.3.0-beta.5/opslevel-linux-amd64.tar.gz"
      sha256 "52b8fc5446aecf54559e7a22e1457844fa29362ded81b10b8a168fff753109de"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v0.3.0-beta.5/opslevel-linux-arm.tar.gz"
      sha256 "e51b4d9a9ad47d5c5737d5d35b1c8c863c1ca272bae937a2e99a68c710a3605b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v0.3.0-beta.5/opslevel-linux-arm64.tar.gz"
      sha256 "15cb27a1fea909635b483883a68fc128198969a7b55ea4d219a4ef9c901a0745"
    end
  end

  depends_on "jq"

  def install
    bin.install "opslevel"
  end

  test do
    system "#{bin}/opslevel version"
  end
end
