# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Opslevel Command Line Utility"
  homepage "https://www.opslevel.com/"
  version "2022.7.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v2022.7.15/opslevel-darwin-amd64.tar.gz"
      sha256 "227ca8c6d7eb6f192b4b9915270f723a1e9dfb000bcc8dcd9626fddf18a311b6"

      def install
        bin.install "opslevel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpsLevel/cli/releases/download/v2022.7.15/opslevel-darwin-arm64.tar.gz"
      sha256 "5cd3683acca4364e0507dcfd879dbba21fb622a7f4ddb4a71c773e7bfff9c818"

      def install
        bin.install "opslevel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v2022.7.15/opslevel-linux-arm64.tar.gz"
      sha256 "66a5cab232f8ed6393a2fa779e5e8357f74ad04ed7f84b7089562cfc9ea13298"

      def install
        bin.install "opslevel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/cli/releases/download/v2022.7.15/opslevel-linux-amd64.tar.gz"
      sha256 "3e0facfdcb23abe1af55b2208da702fafca572428c71885b7d58cfd916d92482"

      def install
        bin.install "opslevel"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/cli/releases/download/v2022.7.15/opslevel-linux-arm.tar.gz"
      sha256 "662722d48c3ab7df5efaf18a63f04a995d068e4fac624662c09167cfea306e62"

      def install
        bin.install "opslevel"
      end
    end
  end

  depends_on "jq"

  test do
    system "#{bin}/opslevel version"
  end
end
