# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlOpslevel < Formula
  desc "Command line tool that enables you to import & reconcile services with OpsLevel"
  homepage "https://www.opslevel.com/"
  version "v0.4.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/kubectl-opslevel/releases/download/v0.4.0/kubectl-opslevel_darwin_amd64.tar.gz"
      sha256 "08f2105322818f04897a3111e5889f8b765e9fc59dba057ab7f15330feb398fb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/kubectl-opslevel/releases/download/v0.4.0/kubectl-opslevel_linux_amd64.tar.gz"
      sha256 "4e78eb4e56c57783f0fe9a58f353657438662fee1c342a69ebe69f280173b4ff"
    end
  end

  depends_on "jq"

  def install
    bin.install "kubectl-opslevel"
  end

  test do
    system "#{bin}/kubectl-opslevel version"
  end
end
