# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpslevelAgent < Formula
  desc "Main repository for the OpsLevel agent"
  homepage "https://www.opslevel.com/"
  version "2025.7.22"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "3281e36fff7df13dbce5b22f6141e3d7245a503aa85bef27266e4d4c7fcfb786"

      def install
        bin.install "opslevel-agent"
      end
    end
    on_arm do
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "3f21002eafdc9dc72c7036642cb9b5097cfdeedb736e4f1923a71107d175937f"

      def install
        bin.install "opslevel-agent"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "408291b065ff5e0f6e1b35a6ad86a98158cfe39e6dcc2c8948a061d4b8c0a8c4"
      def install
        bin.install "opslevel-agent"
      end
    end
    on_arm do
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "adffa01e1607c3834f4fbd4be82efa16b50d669e55cf7712e7dffc9df516642f"
      def install
        bin.install "opslevel-agent"
      end
    end
  end

  test do
    system "#{bin}/opslevel-agent version"
  end
end
