# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpslevelMcp < Formula
  desc "Opslevel MCP Server"
  homepage "https://www.opslevel.com/"
  version "2025.5.28"
  license "MIT"

  depends_on "jq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpsLevel/opslevel-mcp/releases/download/v2025.5.28/opslevel-mcp-darwin-amd64.tar.gz"
      sha256 "c609f870c12ac4b0dfaa0acfa46e00a4bad6a0df2de3e32af6fa4b73e7444574"

      def install
        bin.install "opslevel-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpsLevel/opslevel-mcp/releases/download/v2025.5.28/opslevel-mcp-darwin-arm64.tar.gz"
      sha256 "36da42e2f67c8dc8711711809feba4565d8c6de76fc29a02bc7ca92ebe86cd62"

      def install
        bin.install "opslevel-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/opslevel-mcp/releases/download/v2025.5.28/opslevel-mcp-linux-amd64.tar.gz"
      sha256 "bf3c332b052594f985f97f212457dbc9d9c9c0792af1fd2109c59a05fbd98e26"
      def install
        bin.install "opslevel-mcp"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/opslevel-mcp/releases/download/v2025.5.28/opslevel-mcp-linux-arm.tar.gz"
      sha256 "f3556ffefc36aeb9eb37fc346bbfc7c2c35e9cf231d14577c401284e83b80feb"
      def install
        bin.install "opslevel-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/OpsLevel/opslevel-mcp/releases/download/v2025.5.28/opslevel-mcp-linux-arm64.tar.gz"
      sha256 "a451dbcc81f7e1da6d1d450ac4d00e5dd6dbde84249a4c00d820cda29e26aab1"
      def install
        bin.install "opslevel-mcp"
      end
    end
  end

  test do
    system "#{bin}/opslevel-mcp version"
  end
end
