# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpslevelAgent < Formula
  desc "Main repository for the OpsLevel agent"
  homepage "https://www.opslevel.com/"
  version "2025.7.22"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "d67af6902387175e8f69fd1ed1c92d9a969d8e5e273f568bd8968c631f154f2b"

      def install
        bin.install "opslevel-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "a246123d3a28fc3bd4557e1ca5d9a6b0dabd464f2efb8176ef74952ec585afce"

      def install
        bin.install "opslevel-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "28cdf0fa24bfb69011b2c12a2bb03ddc2c5f2e3a7458ed176f92d36227aea1bc"
      def install
        bin.install "opslevel-agent"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/opslevel/opslevel-agent/archive/refs/tags/v2025.7.22.tar.gz"
      sha256 "912e8696891954b8aad9812fdedc7bcdafcab0d7da4553f544c939145abb86c9"
      def install
        bin.install "opslevel-agent"
      end
    end
  end

  test do
    system "#{bin}/opslevel-agent version"
  end
end
